// File generated by FlutterFire CLI or configured manually.
// Replace with your real project credentials from the Firebase Console if available.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApexFixPlaceholderWebKey12345',
    appId: '1:100000000000:web:apexfixproappweb',
    messagingSenderId: '100000000000',
    projectId: 'apexfix-homeservices',
    authDomain: 'apexfix-homeservices.firebaseapp.com',
    storageBucket: 'apexfix-homeservices.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApexFixPlaceholderAndroidKey12345',
    appId: '1:100000000000:android:apexfixproapp',
    messagingSenderId: '100000000000',
    projectId: 'apexfix-homeservices',
    storageBucket: 'apexfix-homeservices.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApexFixPlaceholderIosKey12345',
    appId: '1:100000000000:ios:apexfixproapp',
    messagingSenderId: '100000000000',
    projectId: 'apexfix-homeservices',
    storageBucket: 'apexfix-homeservices.appspot.com',
    iosBundleId: 'com.apexfix.technicianApp',
  );
}
