import '../models/models.dart';

class SeedData {
  // -------------------------------------------------------------
  // Categories
  // -------------------------------------------------------------
  static final List<ServiceCategory> categories = [
    ServiceCategory(
      id: 'cat_hvac',
      title: 'AC & Cooling',
      iconName: 'wind',
      colorBg: '#EFF6FF',
      colorText: '#1D4ED8',
      description: 'Master repair, deep jet wash, compressor replacement & refrigerant refilling.',
      startingPrice: 2500,
      bannerImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
    ),
    ServiceCategory(
      id: 'cat_electrical',
      title: 'Electrical',
      iconName: 'zap',
      colorBg: '#FEF3C7',
      colorText: '#B45309',
      description: 'Short circuit repairs, distribution boxes, smart touch switches & wiring overhaul.',
      startingPrice: 1800,
      bannerImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop&q=80',
    ),
    ServiceCategory(
      id: 'cat_plumbing',
      title: 'Plumbing',
      iconName: 'droplet',
      colorBg: '#ECFDF5',
      colorText: '#047857',
      description: 'Water leak detection, sanitary fittings, water booster pumps & geyser repair.',
      startingPrice: 2000,
      bannerImage: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=800&auto=format&fit=crop&q=80',
    ),
    ServiceCategory(
      id: 'cat_appliance',
      title: 'Appliances',
      iconName: 'cpu',
      colorBg: '#F3E8FF',
      colorText: '#7E22CE',
      description: 'Inverter refrigerators, automatic washing machines, microwaves & dispensers.',
      startingPrice: 2200,
      bannerImage: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    ),
    ServiceCategory(
      id: 'cat_carpentry',
      title: 'Carpentry',
      iconName: 'hammer',
      colorBg: '#FFF7ED',
      colorText: '#C2410C',
      description: 'Smart door locks, wardrobe sliding tracks, hydraulic hinges & bespoke woodwork.',
      startingPrice: 2000,
      bannerImage: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&auto=format&fit=crop&q=80',
    ),
    ServiceCategory(
      id: 'cat_solar',
      title: 'Solar & Inverters',
      iconName: 'sun',
      colorBg: '#FEFCE8',
      colorText: '#A16207',
      description: 'Hybrid solar inverter diagnostics, solar panel efficiency check & battery maintenance.',
      startingPrice: 2000,
      bannerImage: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80',
    ),
  ];

  // -------------------------------------------------------------
  // Services
  // -------------------------------------------------------------
  static final List<ServiceItem> services = [
    // AC & Cooling
    ServiceItem(
      id: 'srv_ac_deep_wash',
      categoryId: 'cat_hvac',
      title: 'Inverter AC Deep Jet Wash & Coil Cleaning',
      description: 'Comprehensive high-pressure pressure pump wash of indoor coil, blower, blower wheel, drain tray, and outdoor condenser.',
      basePrice: 2500,
      durationMinutes: 60,
      features: [
        'High-pressure chemical jet wash',
        'Drain pipe unclogging & deodorization',
        'Amperage and cooling delta-T test',
        '30-day leak-free service warranty',
      ],
    ),
    ServiceItem(
      id: 'srv_ac_gas_refill',
      categoryId: 'cat_hvac',
      title: 'AC Refrigerant Gas (R410A / R32) Refill',
      description: 'Nitrogen pressure leak testing, vacuum pump evacuation, and precise digital scale gas charging.',
      basePrice: 4800,
      durationMinutes: 45,
      features: [
        'Nitrogen pressure leak test',
        'Double-stage vacuum pump evacuation',
        'Genuine Honeywell / Chemours refrigerant',
        '60-day pressure warranty',
      ],
    ),
    ServiceItem(
      id: 'srv_ac_pcb_repair',
      categoryId: 'cat_hvac',
      title: 'Inverter AC PCB Board Repair & Diagnostics',
      description: 'Bench testing of microcontroller, IGBT inverter modules, sensor replacements, and error code troubleshooting.',
      basePrice: 3500,
      durationMinutes: 90,
      features: [
        'Component-level motherboard repair',
        'E6 / F3 / H6 error code fix',
        'OEM replacement relays & capacitors',
      ],
    ),
    ServiceItem(
      id: 'srv_ac_install',
      categoryId: 'cat_hvac',
      title: 'Split AC Dismantle & Reinstallation',
      description: 'Safe refrigerant lock-in, bracket wall mounting, copper flare connection, and insulation wrapping.',
      basePrice: 4000,
      durationMinutes: 120,
      features: [
        'Zero refrigerant loss pump-down',
        'Heavy gauge outdoor wall brackets',
        'Vacuuming before valve release',
      ],
    ),

    // Electrical
    ServiceItem(
      id: 'srv_elec_db_overhaul',
      categoryId: 'cat_electrical',
      title: 'Distribution Box (DB) & Breaker Overhaul',
      description: 'Replacing tripped circuit breakers, phase load balancing, neutral bar tightening, and surge protector installation.',
      basePrice: 2200,
      durationMinutes: 60,
      features: [
        'Schneider / Hager MCB testing',
        'Thermal camera loose terminal scan',
        'Load phase balancing across phases',
      ],
    ),
    ServiceItem(
      id: 'srv_elec_short_circuit',
      categoryId: 'cat_electrical',
      title: 'Concealed Wiring Short Circuit Diagnostic',
      description: 'Trace ground faults, burnt neutral loops, and electrical shorts inside walls with megohmmeter.',
      basePrice: 3000,
      durationMinutes: 90,
      features: [
        'Megger insulation resistance testing',
        'Concealed conduit wire pulling',
        'Fire hazard safety inspection',
      ],
    ),
    ServiceItem(
      id: 'srv_elec_smart_switch',
      categoryId: 'cat_electrical',
      title: 'Smart Wi-Fi Switchboard & Touch Panel Setup',
      description: 'Retrofit standard mechanical switchboards with Tuya/Sonoff smart touch panels, Wi-Fi pairing, and app config.',
      basePrice: 1800,
      durationMinutes: 45,
      features: [
        'Neutral wire routing if needed',
        'Google Home / Alexa integration',
        'Capacitive touch calibration',
      ],
    ),
    ServiceItem(
      id: 'srv_elec_ups_wiring',
      categoryId: 'cat_electrical',
      title: 'UPS & Battery Inverter Backup Wiring',
      description: 'Dedicated inverter output line separation, battery terminal anti-corrosion coating, and heavy DC cabling.',
      basePrice: 2500,
      durationMinutes: 60,
      features: [
        'Dedicated UPS breaker installation',
        'Heavy gauge copper DC cable lugs',
        'Voltage changeover relay testing',
      ],
    ),

    // Plumbing
    ServiceItem(
      id: 'srv_plumb_leak_fix',
      categoryId: 'cat_plumbing',
      title: 'Water Leak Detection & Concealed Pipe Repair',
      description: 'Acoustic leak detection, floor tile surgical cutting, PPRC / GI pipe replacement, and pressure testing.',
      basePrice: 2000,
      durationMinutes: 60,
      features: [
        'Minimal demolition approach',
        'High-grade PPRC fusion welding',
        '10 bar static water pressure test',
      ],
    ),
    ServiceItem(
      id: 'srv_plumb_geyser_service',
      categoryId: 'cat_plumbing',
      title: 'Instant / Storage Geyser Servicing & Element Fix',
      description: 'De-scaling water jacket, replacing thermopile/thermostat, safety relief valve testing, and burner tuning.',
      basePrice: 2400,
      durationMinutes: 45,
      features: [
        'Calcium scale removal',
        'Gas pilot safety shutoff test',
        'Magnesium anode rod inspection',
      ],
    ),
    ServiceItem(
      id: 'srv_plumb_water_pump',
      categoryId: 'cat_plumbing',
      title: 'Automatic Water Booster Pump Maintenance',
      description: 'Mechanical seal leak fix, pressure tank bladder inflation, impeller unjamming, and auto-cut controller repair.',
      basePrice: 2800,
      durationMinutes: 75,
      features: [
        'Italian mechanical seal replacement',
        'Digital flow switch adjustment',
        'Overheating relay check',
      ],
    ),
    ServiceItem(
      id: 'srv_plumb_sanitary',
      categoryId: 'cat_plumbing',
      title: 'Luxury Vanity, Commode & Sanitary Fitting',
      description: 'Installation of wall-hung vanities, concealed commode cisterns, chrome mixer showers, and silicone sealing.',
      basePrice: 3200,
      durationMinutes: 90,
      features: [
        'Anti-fungal silicone water sealing',
        'Precision spirit-level alignment',
        'Leak-proof P-trap & drain coupling',
      ],
    ),

    // Appliances
    ServiceItem(
      id: 'srv_app_fridge',
      categoryId: 'cat_appliance',
      title: 'Inverter Refrigerator Gas & Inverter Board Fix',
      description: 'R600a eco-gas charging, defrost timer/bi-metal replacement, capillary tube flushing, and compressor testing.',
      basePrice: 4500,
      durationMinutes: 90,
      features: [
        'Explosion-safe R600a charging unit',
        'Evaporator coil defrost test',
        'Door gasket magnetic seal restoration',
      ],
    ),
    ServiceItem(
      id: 'srv_app_washer',
      categoryId: 'cat_appliance',
      title: 'Automatic Washing Machine Drum & Motor Repair',
      description: 'Repairing error codes (E1, E2, E3), gearbox bearing replacement, drain pump unclogging, and suspension rods.',
      basePrice: 2600,
      durationMinutes: 60,
      features: [
        'Direct drive / inverter motor diagnostics',
        'Heavy-duty suspension shock dampers',
        'Drain valve solenoid replacement',
      ],
    ),
    ServiceItem(
      id: 'srv_app_microwave',
      categoryId: 'cat_appliance',
      title: 'Microwave Oven Magnetron & Spark Repair',
      description: 'Replacing high voltage diode, capacitor, mica wave-guide sheet, door safety interlock switches, and magnetron.',
      basePrice: 2200,
      durationMinutes: 45,
      features: [
        'High voltage transformer radiation check',
        'Mica sheet spark isolation',
        'Turntable motor gearbox fix',
      ],
    ),

    // Carpentry
    ServiceItem(
      id: 'srv_carp_smart_lock',
      categoryId: 'cat_carpentry',
      title: 'Smart Digital Door Lock Installation',
      description: 'Precision mortise chiseled cutting for biometric fingerprint, RFID keypad smart locks on wood and solid core doors.',
      basePrice: 2500,
      durationMinutes: 60,
      features: [
        'Deadbolt mortise router template jig',
        'Fingerprint & emergency key verification',
        'Weather strip door draft tuning',
      ],
    ),
    ServiceItem(
      id: 'srv_carp_wardrobe',
      categoryId: 'cat_carpentry',
      title: 'Wardrobe Sliding Track & Soft-Close Hinges',
      description: 'Re-aligning misaligned wardrobe sliding doors, installing soft-close German hydraulic hinges, and drawer slides.',
      basePrice: 2000,
      durationMinutes: 60,
      features: [
        'Heavy-duty ball bearing roller wheels',
        'Self-closing damping mechanism',
        'Drawer bottom reinforcement',
      ],
    ),

    // Solar & Inverters
    ServiceItem(
      id: 'srv_solar_inverter_diag',
      categoryId: 'cat_solar',
      title: 'Hybrid Solar Inverter Diagnostic & Config',
      description: 'Troubleshooting fault codes (Fault 01, 04, 08, 51), solar MPPT charging calibration, and lithium battery protocol pairing.',
      basePrice: 5000,
      durationMinutes: 90,
      features: [
        'Inverex / Growatt / Fronus parameter tuning',
        'PV array string VOC & ISC measurement',
        'BMS communication protocol setup',
      ],
    ),
    ServiceItem(
      id: 'srv_solar_panel_test',
      categoryId: 'cat_solar',
      title: 'Solar Rooftop Array Efficiency & Thermal Scan',
      description: 'Thermal drone/infrared hotspot check, MC4 connector crimp check, string combiner box maintenance, and cleaning check.',
      basePrice: 6500,
      durationMinutes: 120,
      features: [
        'Infrared thermal hotspot detection',
        'DC earth grounding impedance test',
        'String current clamping analysis',
      ],
    ),
  ];

  // -------------------------------------------------------------
  // Verified Technicians
  // -------------------------------------------------------------
  static final List<Technician> technicians = [
    Technician(
      id: 'tech_tariq_01',
      fullName: 'Tariq Mahmood',
      email: 'tariq.hvac@apexfix.pk',
      phoneNumber: '+92 300 4567891',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80',
      specialties: ['AC & Cooling', 'HVAC Diagnostics'],
      rating: 4.95,
      reviewCount: 64,
      completedJobsCount: 142,
      availability: TechnicianAvailability.online,
      currentLatitude: 31.4750,
      currentLongitude: 74.3780,
      vehicleInfo: 'Honda CD 70 (Custom Tool Trunk - LEB-4291)',
      bio: 'Certified Senior HVAC Technician with 8+ years experience in inverter ACs, VRF systems, and commercial refrigeration.',
    ),
    Technician(
      id: 'tech_kamran_02',
      fullName: 'Muhammad Kamran Ali',
      email: 'kamran.electric@apexfix.pk',
      phoneNumber: '+92 321 8765432',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      specialties: ['Electrical', 'Solar & Inverters'],
      rating: 4.90,
      reviewCount: 52,
      completedJobsCount: 118,
      availability: TechnicianAvailability.online,
      currentLatitude: 31.5120,
      currentLongitude: 74.3540,
      vehicleInfo: 'Suzuki GD 110 (LHR-8910)',
      bio: 'Licensed Electrician & Certified Solar Installer. Specialized in three-phase DB panels, hybrid solar inverters, and home automation.',
    ),
    Technician(
      id: 'tech_zubair_03',
      fullName: 'Zubair Ahmed',
      email: 'zubair.plumbing@apexfix.pk',
      phoneNumber: '+92 333 9876543',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      specialties: ['Plumbing', 'Geyser Repair'],
      rating: 4.88,
      reviewCount: 41,
      completedJobsCount: 95,
      availability: TechnicianAvailability.online,
      currentLatitude: 31.4890,
      currentLongitude: 74.3120,
      vehicleInfo: 'Honda Pridor (Tool Carrier - MN-3142)',
      bio: 'Master Pipefitter with expert skills in acoustic water leak detection, PPRC fusion, luxury sanitary fixtures, and booster pumps.',
    ),
    Technician(
      id: 'tech_bilal_04',
      fullName: 'Bilal Hassan',
      email: 'bilal.appliances@apexfix.pk',
      phoneNumber: '+92 345 1234567',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      specialties: ['Appliances', 'Refrigeration'],
      rating: 4.92,
      reviewCount: 38,
      completedJobsCount: 84,
      availability: TechnicianAvailability.online,
      currentLatitude: 31.5430,
      currentLongitude: 74.3670,
      vehicleInfo: 'Yamaha YBR 125 (LED-7711)',
      bio: 'Electronics engineer turned home appliance specialist. Expert in inverter refrigerators, front-load washers, and induction cooktops.',
    ),
    Technician(
      id: 'tech_rashid_05',
      fullName: 'Rashid Mehmood',
      email: 'rashid.carpentry@apexfix.pk',
      phoneNumber: '+92 312 3456789',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
      specialties: ['Carpentry', 'Locksmith'],
      rating: 4.89,
      reviewCount: 29,
      completedJobsCount: 67,
      availability: TechnicianAvailability.offline,
      currentLatitude: 31.4600,
      currentLongitude: 74.3900,
      vehicleInfo: 'Suzuki Ravi Pickup (LHR-1402)',
      bio: 'Master Craftsman with 12 years of custom woodwork, biometric door lock installations, kitchen cabinetry, and antique furniture restoration.',
    ),
  ];

  // -------------------------------------------------------------
  // Customers
  // -------------------------------------------------------------
  static final List<Customer> customers = [
    Customer(
      id: 'cust_hamza_01',
      fullName: 'Hamza Malik',
      email: 'hamza.malik@gmail.com',
      phoneNumber: '+92 301 2345678',
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80',
      createdAt: '2025-01-15T10:00:00.000Z',
      defaultAddressId: 'addr_hamza_home',
      addresses: [
        Address(
          id: 'addr_hamza_home',
          label: 'Home',
          street: 'House 42, Street 8, Sector C, Phase 5 DHA',
          city: 'Lahore',
          state: 'Punjab',
          zipCode: '54792',
          latitude: 31.4682,
          longitude: 74.3891,
          isDefault: true,
        ),
        Address(
          id: 'addr_hamza_office',
          label: 'Office',
          street: 'Level 4, Arfa Software Technology Park, Ferozepur Road',
          city: 'Lahore',
          state: 'Punjab',
          zipCode: '54600',
          latitude: 31.4758,
          longitude: 74.3412,
          isDefault: false,
        ),
      ],
    ),
    Customer(
      id: 'cust_ayesha_02',
      fullName: 'Ayesha Khan',
      email: 'ayesha.khan@gmail.com',
      phoneNumber: '+92 322 8765432',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      createdAt: '2025-02-10T14:30:00.000Z',
      defaultAddressId: 'addr_ayesha_apt',
      addresses: [
        Address(
          id: 'addr_ayesha_apt',
          label: 'Apartment',
          street: 'Apt 304, Gulberg Heights, Main Boulevard Gulberg II',
          city: 'Lahore',
          state: 'Punjab',
          zipCode: '54660',
          latitude: 31.5170,
          longitude: 74.3580,
          isDefault: true,
        ),
      ],
    ),
    Customer(
      id: 'cust_zainab_03',
      fullName: 'Zainab Tariq',
      email: 'zainab.tariq@gmail.com',
      phoneNumber: '+92 334 5678901',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      createdAt: '2025-03-01T09:15:00.000Z',
      defaultAddressId: 'addr_zainab_home',
      addresses: [
        Address(
          id: 'addr_zainab_home',
          label: 'Home',
          street: 'House 15-B, Street 22, Sector F-7/2',
          city: 'Islamabad',
          state: 'Islamabad Capital Territory',
          zipCode: '44000',
          latitude: 33.7215,
          longitude: 73.0560,
          isDefault: true,
        ),
      ],
    ),
  ];

  // -------------------------------------------------------------
  // Initial Bookings
  // -------------------------------------------------------------
  static final List<Booking> initialBookings = [
    // 1. In-progress AC Service assigned to Tariq Mahmood
    Booking(
      id: 'bk_live_001',
      bookingNumber: 'APX-84920',
      customerId: 'cust_hamza_01',
      technicianId: 'tech_tariq_01',
      technician: technicians[0],
      serviceCategoryId: 'cat_hvac',
      serviceId: 'srv_ac_deep_wash',
      serviceName: 'Inverter AC Deep Jet Wash & Coil Cleaning',
      serviceCategoryName: 'AC & Cooling',
      complaintTitle: 'Master bedroom 1.5-ton AC cooling weak & water leaking',
      complaintDescription: 'The indoor split unit is throwing lukewarm air and water is dripping from the right side of the casing. Needs thorough jet wash and drain pipe inspection.',
      address: customers[0].addresses[0],
      scheduledDate: 'Today',
      scheduledTimeSlot: 'Urgent Dispatch (Within 45 mins)',
      status: BookingStatus.onTheWay,
      serviceCharge: ServiceCharge(
        baseServiceFee: 2500,
        partsCost: 0,
        tax: 125,
        discount: 200,
        total: 2425,
      ),
      createdAt: DateTime.now().subtract(const Duration(minutes: 25)).toIso8601String(),
      updatedAt: DateTime.now().subtract(const Duration(minutes: 5)).toIso8601String(),
      estimatedArrivalMinutes: 12,
    ),

    // 2. Newly submitted request searching for technician
    Booking(
      id: 'bk_live_002',
      bookingNumber: 'APX-93112',
      customerId: 'cust_ayesha_02',
      technicianId: null,
      technician: null,
      serviceCategoryId: 'cat_plumbing',
      serviceId: 'srv_plumb_leak_fix',
      serviceName: 'Water Leak Detection & Concealed Pipe Repair',
      serviceCategoryName: 'Plumbing',
      complaintTitle: 'Water seepage behind master bathroom tiles',
      complaintDescription: 'Noticeable moisture and paint bubbling on the wall adjacent to the shower mixer. Suspected concealed elbow joint pinhole leak.',
      address: customers[1].addresses[0],
      scheduledDate: 'Today',
      scheduledTimeSlot: 'Afternoon (02:00 PM - 04:00 PM)',
      status: BookingStatus.searchingTechnician,
      serviceCharge: ServiceCharge(
        baseServiceFee: 2000,
        partsCost: 0,
        tax: 100,
        discount: 0,
        total: 2100,
      ),
      createdAt: DateTime.now().subtract(const Duration(minutes: 8)).toIso8601String(),
      updatedAt: DateTime.now().subtract(const Duration(minutes: 8)).toIso8601String(),
      estimatedArrivalMinutes: null,
    ),

    // 3. Historical completed electrical booking
    Booking(
      id: 'bk_live_003',
      bookingNumber: 'APX-71045',
      customerId: 'cust_hamza_01',
      technicianId: 'tech_kamran_02',
      technician: technicians[1],
      serviceCategoryId: 'cat_electrical',
      serviceId: 'srv_elec_db_overhaul',
      serviceName: 'Distribution Box (DB) & Breaker Overhaul',
      serviceCategoryName: 'Electrical',
      complaintTitle: 'Main 63A breaker tripping on AC load',
      complaintDescription: 'Breaker was overheating due to loose neutral busbar and faulty 32A single pole MCB. Replaced with genuine Schneider MCB and balanced phase loads.',
      address: customers[0].addresses[0],
      scheduledDate: '12 Sep 2026',
      scheduledTimeSlot: '11:00 AM - 01:00 PM',
      status: BookingStatus.completed,
      serviceCharge: ServiceCharge(
        baseServiceFee: 2200,
        partsCost: 850,
        tax: 152,
        discount: 0,
        total: 3202,
      ),
      createdAt: DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      updatedAt: DateTime.now().subtract(const Duration(days: 2, hours: 2)).toIso8601String(),
      estimatedArrivalMinutes: 0,
    ),
  ];
}

