import '../models/models.dart';

class SeedData {
  static final List<Technician> technicians = [
    Technician(
      id: 'tech_tariq_01',
      fullName: 'Tariq Mahmood',
      email: 'tariq.hvac@apexfix.pk',
      phoneNumber: '+92 300 4567891',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80',
      specialties: ['AC & Cooling', 'HVAC Diagnostics'],
      rating: 4.95,
      reviewCount: 64,
      completedJobsCount: 142,
      availability: TechnicianAvailability.online,
      currentLatitude: 31.4750,
      currentLongitude: 74.3780,
      vehicleInfo: 'Honda CD 70 (Custom Tool Trunk - LEB-4291)',
      bio: 'Certified Senior HVAC Technician with 8+ years experience in inverter ACs, VRF systems, and commercial refrigeration.',
      todayEarnings: 4500.0,
      totalWalletBalance: 24800.0,
      isVerified: true,
    ),
    Technician(
      id: 'tech_kamran_02',
      fullName: 'Muhammad Kamran Ali',
      email: 'kamran.electric@apexfix.pk',
      phoneNumber: '+92 321 8765432',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      specialties: ['Electrical', 'Solar & Inverters'],
      rating: 4.90,
      reviewCount: 52,
      completedJobsCount: 118,
      availability: TechnicianAvailability.online,
      currentLatitude: 31.5120,
      currentLongitude: 74.3540,
      vehicleInfo: 'Suzuki GD 110 (LHR-8910)',
      bio: 'Licensed Electrician & Certified Solar Installer. Specialized in three-phase DB panels, hybrid solar inverters, and home automation.',
      todayEarnings: 3200.0,
      totalWalletBalance: 19500.0,
      isVerified: true,
    ),
    Technician(
      id: 'tech_zubair_03',
      fullName: 'Zubair Ahmed',
      email: 'zubair.plumbing@apexfix.pk',
      phoneNumber: '+92 333 9876543',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      specialties: ['Plumbing', 'Geyser Repair'],
      rating: 4.88,
      reviewCount: 41,
      completedJobsCount: 95,
      availability: TechnicianAvailability.online,
      currentLatitude: 31.4890,
      currentLongitude: 74.3120,
      vehicleInfo: 'Honda Pridor (Tool Carrier - MN-3142)',
      bio: 'Master Pipefitter with expert skills in acoustic water leak detection, PPRC fusion, luxury sanitary fixtures, and booster pumps.',
      todayEarnings: 2800.0,
      totalWalletBalance: 16200.0,
      isVerified: true,
    ),
  ];

  static final List<TechJob> initialIncomingJobs = [
    TechJob(
      id: 'bk_live_002',
      bookingNumber: 'APX-93112',
      customerName: 'Ayesha Khan',
      customerPhone: '+92 322 8765432',
      serviceCategoryId: 'cat_plumbing',
      serviceCategoryName: 'Plumbing',
      serviceName: 'Water Leak Detection & Concealed Pipe Repair',
      complaintTitle: 'Water seepage behind master bathroom tiles',
      complaintDescription: 'Noticeable moisture and paint bubbling on the wall adjacent to the shower mixer. Suspected concealed elbow joint pinhole leak.',
      address: Address(
        id: 'addr_ayesha_apt',
        label: 'Apartment',
        street: 'Apt 304, Gulberg Heights, Main Boulevard Gulberg II',
        city: 'Lahore',
        state: 'Punjab',
        zipCode: '54660',
        latitude: 31.5170,
        longitude: 74.3580,
      ),
      scheduledDate: 'Today',
      scheduledTimeSlot: 'Afternoon (02:00 PM - 04:00 PM)',
      status: BookingStatus.searchingTechnician,
      serviceCharge: ServiceCharge(
        baseServiceFee: 2000,
        tax: 100,
        total: 2100,
      ),
      technicianPayout: 1700.0,
      createdAt: DateTime.now().subtract(const Duration(minutes: 8)).toIso8601String(),
    ),
    TechJob(
      id: 'bk_live_004',
      bookingNumber: 'APX-65021',
      customerName: 'Zainab Tariq',
      customerPhone: '+92 334 5678901',
      serviceCategoryId: 'cat_hvac',
      serviceCategoryName: 'AC & Cooling',
      serviceName: 'AC Refrigerant Gas (R410A) Refill & Leak Fix',
      complaintTitle: 'Split AC blowing normal fan air without cooling',
      complaintDescription: '1.5 ton split AC outdoor unit running but line is not freezing. Suspected gas leak from service valve.',
      address: Address(
        id: 'addr_zainab_home',
        label: 'Home',
        street: 'House 15-B, Street 22, Sector F-7/2',
        city: 'Islamabad',
        state: 'ICT',
        zipCode: '44000',
        latitude: 33.7215,
        longitude: 73.0560,
      ),
      scheduledDate: 'Today',
      scheduledTimeSlot: 'Urgent Dispatch (Within 45 mins)',
      status: BookingStatus.searchingTechnician,
      serviceCharge: ServiceCharge(
        baseServiceFee: 4800,
        tax: 240,
        total: 5040,
      ),
      technicianPayout: 4000.0,
      createdAt: DateTime.now().subtract(const Duration(minutes: 3)).toIso8601String(),
    ),
  ];

  static final List<TechJob> initialJobsHistory = [
    TechJob(
      id: 'bk_live_003',
      bookingNumber: 'APX-71045',
      customerName: 'Hamza Malik',
      customerPhone: '+92 301 2345678',
      serviceCategoryId: 'cat_electrical',
      serviceCategoryName: 'Electrical',
      serviceName: 'Distribution Box (DB) & Breaker Overhaul',
      complaintTitle: 'Main 63A breaker tripping on AC load',
      complaintDescription: 'Replaced burnt 32A MCB breaker and balanced phases. Safe and operational.',
      address: Address(
        id: 'addr_hamza_home',
        label: 'Home',
        street: 'House 42, Street 8, Sector C, Phase 5 DHA',
        city: 'Lahore',
        state: 'Punjab',
        zipCode: '54792',
        latitude: 31.4682,
        longitude: 74.3891,
      ),
      scheduledDate: '12 Sep 2026',
      scheduledTimeSlot: '11:00 AM - 01:00 PM',
      status: BookingStatus.completed,
      serviceCharge: ServiceCharge(
        baseServiceFee: 2200,
        tax: 152,
        total: 3202,
        partsFee: 850,
      ),
      technicianPayout: 2500.0,
      createdAt: DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      acceptedAt: DateTime.now().subtract(const Duration(days: 2, hours: 3)).toIso8601String(),
      completedAt: DateTime.now().subtract(const Duration(days: 2, hours: 1)).toIso8601String(),
      customerRating: 5.0,
      customerReview: 'Arrived right on time. Very professional technician who quickly resolved the tripping issue!',
    ),
  ];
}

